### ISSUE TITLE
Add screenshots to the README

### ISSUE THREAD

**Issue by busybox11** [ryoon/youtube-dl-web-ui#1]
Hey,

I was looking for youtube-dl web interfaces, and I found yours.

Unfortunately it doesn't have any screenshots. You might want to add some, so people (like me) will be able to know how it looks like, how is the UI/UX, and web developers how they can improve it.

Not having screenshots isn't great, since most of the time, people (including me sometimes) don't take a look at the project at all.

**Comment by ryoon** [comment]
I have just added a screenshot image to README.md.

**Comment by busybox11** [comment]
Nice, thanks!
